/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pootrabalho27;

/**
 *
 * @author vitao375
 */
public class FrameEletrica extends javax.swing.JFrame {

    /**
     * Creates new form FrameEletrica
     */
    public FrameEletrica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTipoPeca1 = new javax.swing.JLabel();
        jTextFieldNome1 = new javax.swing.JTextField();
        jLabelModelo1 = new javax.swing.JLabel();
        jTextFieldFabricante1 = new javax.swing.JTextField();
        jLabelValor1 = new javax.swing.JLabel();
        jLabelQuantidade1 = new javax.swing.JLabel();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelFrabricante1 = new javax.swing.JLabel();
        jTextFieldTipoPeca1 = new javax.swing.JTextField();
        jLabelAmperagem1 = new javax.swing.JLabel();
        jLabelVoltagem1 = new javax.swing.JLabel();
        jLabelTipoSistema1 = new javax.swing.JLabel();
        jTextFieldAmperagem1 = new javax.swing.JTextField();
        jTextFieldQuantidade1 = new javax.swing.JTextField();
        jTextFieldVoltagem1 = new javax.swing.JTextField();
        jButtonVoltar1 = new javax.swing.JButton();
        jTextFieldValor1 = new javax.swing.JTextField();
        jComboBoxTipoSistema1 = new javax.swing.JComboBox<>();
        jButtonSalvar1 = new javax.swing.JButton();
        jTextFieldModelo1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTipoPeca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoPeca1.setText("Tipo da Peça: ");

        jTextFieldNome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelModelo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelModelo1.setText("Modelo: ");

        jTextFieldFabricante1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelValor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValor1.setText("Valor: ");

        jLabelQuantidade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQuantidade1.setText("Quantidade: ");

        jLabelNome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome1.setText("Nome: ");

        jLabelFrabricante1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFrabricante1.setText("Fabricante da peça: ");

        jTextFieldTipoPeca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelAmperagem1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAmperagem1.setText("Amperagem: ");

        jLabelVoltagem1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelVoltagem1.setText("Voltagem:");

        jLabelTipoSistema1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoSistema1.setText("Tipo de Sistema:");

        jTextFieldAmperagem1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAmperagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmperagem1ActionPerformed(evt);
            }
        });

        jTextFieldQuantidade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldQuantidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidade1ActionPerformed(evt);
            }
        });

        jTextFieldVoltagem1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonVoltar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVoltar1.setText("Voltar");

        jTextFieldValor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValor1ActionPerformed(evt);
            }
        });

        jComboBoxTipoSistema1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTipoSistema1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistema de Ignição", "Sistema de Alimentação", "Sistema de Sinalização", "Outro" }));

        jButtonSalvar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSalvar1.setText("Salvar");

        jTextFieldModelo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldModelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModelo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelTipoSistema1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBoxTipoSistema1, 0, 199, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelAmperagem1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelValor1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelTipoPeca1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(51, 51, 51)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNome1)
                                        .addComponent(jTextFieldValor1)
                                        .addComponent(jTextFieldTipoPeca1)
                                        .addComponent(jTextFieldAmperagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelVoltagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabelFrabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldFabricante1)
                                .addComponent(jTextFieldQuantidade1)
                                .addComponent(jTextFieldModelo1)
                                .addComponent(jTextFieldVoltagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                            .addGap(3, 3, 3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonVoltar1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalvar1)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTipoPeca1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo1)
                            .addComponent(jTextFieldTipoPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextFieldModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelValor1)
                                .addComponent(jTextFieldValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelQuantidade1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelNome1)
                                .addComponent(jTextFieldNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldFabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFrabricante1))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVoltagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jTextFieldAmperagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldVoltagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelAmperagem1))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxTipoSistema1)
                        .addComponent(jLabelTipoSistema1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jButtonSalvar1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jButtonVoltar1)))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAmperagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmperagem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmperagem1ActionPerformed

    private void jTextFieldQuantidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantidade1ActionPerformed

    private void jTextFieldValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValor1ActionPerformed

    private void jTextFieldModelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModelo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModelo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEletrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEletrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEletrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEletrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEletrica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JButton jButtonVoltar1;
    private javax.swing.JComboBox<String> jComboBoxTipoSistema1;
    private javax.swing.JLabel jLabelAmperagem1;
    private javax.swing.JLabel jLabelFrabricante1;
    private javax.swing.JLabel jLabelModelo1;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelQuantidade1;
    private javax.swing.JLabel jLabelTipoPeca1;
    private javax.swing.JLabel jLabelTipoSistema1;
    private javax.swing.JLabel jLabelValor1;
    private javax.swing.JLabel jLabelVoltagem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAmperagem1;
    private javax.swing.JTextField jTextFieldFabricante1;
    private javax.swing.JTextField jTextFieldModelo1;
    private javax.swing.JTextField jTextFieldNome1;
    private javax.swing.JTextField jTextFieldQuantidade1;
    private javax.swing.JTextField jTextFieldTipoPeca1;
    private javax.swing.JTextField jTextFieldValor1;
    private javax.swing.JTextField jTextFieldVoltagem1;
    // End of variables declaration//GEN-END:variables
}
