package Frames;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import ClassesPeca.Acessorio;
import ClassesPeca.PecaAuto;
import Lista.ListaPeca;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author vitao375
 */
public class FrameView extends javax.swing.JFrame {

    public ListaPeca lista = new ListaPeca();
    private List<PecaAuto> listaAcessorio = new ArrayList();

    /**
     * Creates new form FrameView
     *
     * @param lista
     */
    public FrameView(ListaPeca lista) {
        //lista.lerArquivo();
        initComponents();
        this.lista = lista;
        try {
            this.lista.lerArquivo();
        }catch(Exception e){
            
        }
        List<PecaAuto> aux;
        this.setLocationRelativeTo(null);
        this.setTitle("Peças Automotivas");
        //Arrumar os Preencher campos para alterar as comboBox também
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBoxBuscaTipo = new javax.swing.JComboBox<>();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPadrao = new javax.swing.JList<>();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonDetalhes = new javax.swing.JButton();
        jButtonBuscarAcessorio = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxBuscaTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxBuscaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por Nome", "Buscar por Fabricante" }));
        jComboBoxBuscaTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxBuscaTipoItemStateChanged(evt);
            }
        });
        jComboBoxBuscaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBuscaTipoActionPerformed(evt);
            }
        });

        jTextFieldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaActionPerformed(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonBuscar.setText("Buscar Peça");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jListPadrao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jListPadrao);

        jButtonIncluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonDetalhes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDetalhes.setText("Detalhes");
        jButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalhesActionPerformed(evt);
            }
        });

        jButtonBuscarAcessorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonBuscarAcessorio.setText("Buscar Acessorio");
        jButtonBuscarAcessorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAcessorioActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxBuscaTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBusca)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBuscarAcessorio, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxBuscaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonBuscarAcessorio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBuscaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBuscaTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBuscaTipoActionPerformed

    private void jTextFieldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        String[] textMessages = {"Elétrica", "Acessorios", "Mecanica", "Cancelar"};
        int x = JOptionPane.showOptionDialog(null, "Escolha o tipo de Peça", "Incluir",
                JOptionPane.WHEN_IN_FOCUSED_WINDOW, JOptionPane.QUESTION_MESSAGE,
                null, textMessages, null);

        switch (x) {
            case 0:
                FrameEletrica abrirEletrica = new FrameEletrica("Incluir", null, lista);
                abrirEletrica.setVisible(true);
                this.dispose();
                break;
            case 1:
                FrameAcessorios abrirAcessorio = new FrameAcessorios("Incluir", null, lista);
                abrirAcessorio.setVisible(true);
                this.dispose();
                break;
            case 2:
                FrameMecanica abrirMecanica = new FrameMecanica("Incluir", null, lista);
                abrirMecanica.setVisible(true);
                this.dispose();
                break;
            default:
                JOptionPane.showMessageDialog(null, "Operação cancelada!");
                break;
        }
    }//GEN-LAST:event_jButtonIncluirActionPerformed
//Buscar por Nome, Buscar por Fabricante
//Peças em Geral, Peças Eletricas, Peças Mecanicas, Acessorios
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String buscaTipo = jComboBoxBuscaTipo.getSelectedItem().toString();
        PecaAuto aux;
        List<PecaAuto> listaAux= new ArrayList();
        if (jTextFieldBusca.getText().trim().equals("")) {
            listaAux = lista.getLista();
            listar(listaAux);
        } else {
            switch (buscaTipo) {

                case "Buscar por Nome":
                    aux = lista.consultaPeca(jTextFieldBusca.getText());
                    if (aux != null) {
                        listaAux.add(aux);
                        listar(listaAux);
                    } else {
                        JOptionPane.showMessageDialog(null, "Não encontrado");
                    }

                    break;
                case "Buscar por Fabricante":
                    aux = lista.consultarFabricante(jTextFieldBusca.getText());
                    if (aux != null) {
                        listaAux.add(aux);
                        listar(listaAux);
                    } else {
                        JOptionPane.showMessageDialog(null, "Não encontrado");
                    }
                    break;
            }
        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboBoxBuscaTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxBuscaTipoItemStateChanged
        jTextFieldBusca.setText("");
    }//GEN-LAST:event_jComboBoxBuscaTipoItemStateChanged

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        String editar = JOptionPane.showInputDialog(null, "Informe o Nome da peca a ser Editada");
        if (editar != null) {
            String[] textMessages = {"Elétrica", "Acessorios", "Mecanica", "Cancelar"};
            int x = JOptionPane.showOptionDialog(null, "Escolha o tipo de Peça", "Editar",
                    JOptionPane.WHEN_IN_FOCUSED_WINDOW, JOptionPane.QUESTION_MESSAGE,
                    null, textMessages, null);

            switch (x) {
                case 0:
                    this.dispose();
                    new FrameEletrica("Editar", editar, lista).setVisible(true);
                    break;
                case 1:
                    FrameAcessorios abrirAcessorio = new FrameAcessorios("Editar", editar, lista);
                    abrirAcessorio.setVisible(true);
                    this.dispose();
                    break;
                case 2:
                    FrameMecanica abrirMecanica = new FrameMecanica("Editar", editar, lista);
                    abrirMecanica.setVisible(true);
                    this.dispose();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Operação cancelada!");
                    break;
            }

        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");
        }

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalhesActionPerformed

        String detalhes = JOptionPane.showInputDialog(null, "Informe o Nome da peca a ser Consultada");
        if (detalhes != null) {
            String[] textMessages = {"Elétrica", "Acessorios", "Mecanica", "Cancelar"};
            int x = JOptionPane.showOptionDialog(null, "Escolha o tipo de Peça", "Detalhes",
                    JOptionPane.WHEN_IN_FOCUSED_WINDOW, JOptionPane.QUESTION_MESSAGE,
                    null, textMessages, null);

            switch (x) {
                case 0:
                    FrameEletrica abrirEletrica = new FrameEletrica("Consultar", detalhes, lista);
                    abrirEletrica.setVisible(true);
                    this.dispose();
                    break;
                case 1:
                    FrameAcessorios abrirAcessorio = new FrameAcessorios("Consultar", detalhes, lista);
                    abrirAcessorio.setVisible(true);
                    this.dispose();
                    break;
                case 2:
                    FrameMecanica abrirMecanica = new FrameMecanica("Consultar", detalhes, lista);
                    abrirMecanica.setVisible(true);
                    this.dispose();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Operação cancelada!");
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");
        }

    }//GEN-LAST:event_jButtonDetalhesActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String excluir = JOptionPane.showInputDialog(null, "Informe o Nome da peca a ser Excluida");
        if (excluir != null) {
            lista.excluir(excluir);
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonBuscarAcessorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAcessorioActionPerformed
        String buscaTipo = jComboBoxBuscaTipo.getSelectedItem().toString();
        PecaAuto aux;
        List<PecaAuto> listaAux;
        if (jTextFieldBusca.getText().trim().equals("")) {
            listaAux = lista.getLista();
            listar(listaAux);
        } else {
            listaAux = new ArrayList();
            switch (buscaTipo) {

                case "Buscar por Nome":
                    aux = lista.consultarNomeA(jTextFieldBusca.getText());
                    if (aux != null) {
                        listaAux.add(aux);
                        listar(listaAux);
                    } else {
                        JOptionPane.showMessageDialog(null, "Não encontrado");
                    }

                    break;
                case "Buscar por Fabricante":
                    aux = lista.consultarFabricanteA(jTextFieldBusca.getText());
                    if (aux != null) {
                        listaAux.add(aux);
                        listar(listaAux);
                    } else {
                        JOptionPane.showMessageDialog(null, "Não encontrado");
                    }
                    break;
            }
        }
    }//GEN-LAST:event_jButtonBuscarAcessorioActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        JOptionPane.showMessageDialog(null, "Obrigado por Usar nosso software :D");
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarAcessorio;
    private javax.swing.JButton jButtonDetalhes;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxBuscaTipo;
    private javax.swing.JList<String> jListPadrao;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBusca;
    // End of variables declaration//GEN-END:variables
    public void listar(List<PecaAuto> peca) {
        DefaultListModel listaPadrao = new DefaultListModel();
        if (peca == null) {
            jListPadrao.setModel(listaPadrao);
        } else {
            for (PecaAuto p : peca) {
                listaPadrao.addElement(p.toString());
            }
            jListPadrao.setModel(listaPadrao);
        }
    }
}
